news_premier_league/news_premier_league/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView




urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html")),
    path('pl/', include('premier_league.urls')),
    path('accounts/profile/', include('premier_league.urls')),
]

news_premier_league/premier_league/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    IndexView,
    StadiumListView,
    TeamListView,
    NewsListView,
    TeamDetailView,
    NewsDetailView,
    StadiumDetailView,
    register,
    profile_view,
    CommentCreateView,
)

app_name = "premier_league"

urlpatterns = [
    path('accounts/profile/', profile_view, name='profile'),
    path('stadiums/', StadiumListView.as_view(), name='stadium_list'),
    path('stadiums/<int:pk>/', StadiumDetailView.as_view(), name='stadium_detail'),
    path('clubs/', TeamListView.as_view(), name='team_list'),
    path('teams/<int:pk>/', TeamDetailView.as_view(), name='team_detail'),
    path('news/', NewsListView.as_view(), name='news_list'),
    path('news/<int:pk>/', NewsDetailView.as_view(), name='news_detail'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='premier_league:index'), name='logout'),
    path('register/', register, name='register'),
    path('', IndexView.as_view(), name='index'),
    path('news/<int:pk>/comment/', CommentCreateView.as_view(), name='create_comment'),

]

news_premier_league/premier_league/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid


# Create your models here.
class Stadium(models.Model):
    name = models.CharField(max_length=50, unique=True)
    location = models.CharField(max_length=50)
    capacity = models.IntegerField(null=False)
    brokeground = models.DateField()
    architect = models.CharField(max_length=20)
    phone = models.CharField(max_length=20, null=True)
    guid = models.CharField(max_length=36, default=uuid.uuid4, unique=True)

    def __str__(self):
        return self.name


class Team(models.Model):
    name = models.CharField(max_length=50, unique=True)
    nicknames = models.CharField(max_length=50, null=True)
    shortname = models.CharField(max_length=50, null=True)
    founded = models.DateField()
    stadium = models.OneToOneField(Stadium, on_delete=models.SET_NULL, null=True, blank=True, related_name='team')
    website = models.CharField(max_length=50)
    league = models.CharField(max_length=20)
    description = models.TextField()
    guid = models.CharField(max_length=36, default=uuid.uuid4, unique=True)

    def __str__(self):
        return f"Team <{self.pk}, {self.name!r}, {self.stadium!r}>"


class Author(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    guid = models.CharField(max_length=36, default=uuid.uuid4, unique=True)

    def __str__(self):
        return self.name


class News(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    shortname = models.CharField(max_length=50, null=True)
    description = models.TextField()
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, related_name='news')
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, related_name='news')
    guid = models.CharField(max_length=36, default=uuid.uuid4, unique=True)

    def __str__(self):
        return self.shortname


class CustomUser(AbstractUser):
    # name = models.CharField(max_length=100)
    # email = models.EmailField(unique=True)
    teams = models.ManyToManyField(Team, related_name='users')
    guid = models.CharField(max_length=36, default=uuid.uuid4, unique=True)
    # guid = models.CharField(max_length=36, unique=True)

    def __str__(self):
        return self.username


class Comments(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    news = models.ForeignKey(News, on_delete=models.CASCADE, null=True, related_name='comments')
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, related_name='comments')
    guid = models.CharField(max_length=36, default=uuid.uuid4, unique=True)

    def __str__(self):
        return f"{self.created_at} - {self.author} - {self.content}"

news_premier_league/premier_league/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2']

news_premier_league/premier_league/views.py
from django.views.generic import ListView, DetailView, TemplateView
from .models import Stadium, Team, News, Comments
from django.contrib.auth import login
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView


class StadiumListView(ListView):
    model = Stadium
    template_name = 'premier_league/stadium_list.html'
    context_object_name = 'stadiums'


class StadiumDetailView(DetailView):
    model = Stadium
    template_name = 'premier_league/stadium_detail.html'
    context_object_name = 'stadium'


class TeamListView(ListView):
    model = Team
    template_name = 'premier_league/team_list.html'
    context_object_name = 'teams'


class TeamDetailView(DetailView):
    model = Team
    template_name = 'premier_league/team_detail.html'
    context_object_name = 'team'


class NewsListView(ListView):
    model = News
    template_name = 'premier_league/news_list.html'
    context_object_name = 'news_list'


class NewsDetailView(DetailView):
    model = News
    template_name = 'premier_league/news_detail.html'
    context_object_name = 'news'


class IndexView(TemplateView):
    template_name = "premier_league/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        news_list = News.objects.all().order_by('-created_at')
        context['news_list'] = news_list
        return context


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('premier_league:index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def profile_view(request):
    user = request.user
    teams = Team.objects.all()
    user_teams = user.teams.all()

    context = {
        'user': user,
        'teams': teams,
        'user_teams': user_teams,
    }
    return render(request, 'profile.html', context)


class CommentCreateView(CreateView):
    model = Comments
    fields = ['content']
    template_name = 'premier_league/comment_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        news = get_object_or_404(News, pk=self.kwargs['pk'])
        context['news'] = news
        context['comments'] = Comments.objects.filter(news=news)
        return context

    def form_valid(self, form):
        news = get_object_or_404(News, pk=self.kwargs['pk'])
        form.instance.news = news
        form.instance.author = self.request.user
        form.save()
        return redirect('premier_league:news_detail', pk=news.pk)

news_premier_league/premier_league/templates/premier_league/comment_form.html
{% extends 'base.html' %}

{% block title %}
    Add Comment
{% endblock %}

{% block body %}
    <div>
        <h2>"{{ news.shortname }}"</h2>
        <p>{{ news.description }}</p>
        <ul>
            {% for comment in comments %}
                <li>
                    {{ comment.content }}<br>
                    <span class="text-muted">
                        Author: {{ comment.author }} | Date: {{ comment.created_at }}
                    </span>
                </li>
            {% empty %}
                <li>No comments yet.</li>
            {% endfor %}
        </ul>
    </div>
    <h1>Add Comment</h1>
    <form method="post" class="form-inline">
        {% csrf_token %}
        <div class="form-group col-auto">
            {{ form.content.label_tag }}
            {{ form.content }}
        </div>
        <button type="submit" class="btn btn-primary ml-2">Add Comment</button>
    </form>
    <ul>
        <li>
            <a href="{% url 'premier_league:index' %}">Back to Home</a>
        </li>
    </ul>
{% endblock %}

news_premier_league/premier_league/templates/premier_league/index.html
{% extends 'base.html' %}

{% block title %}
    Premier League Home
{% endblock %}

{% block body %}
    <div style="display: flex; justify-content: space-between;">
        <div>
            <h1>Welcome to the Premier League</h1>
            <ul>
                <li><a href="{% url 'premier_league:team_list' %}">Clubs</a></li>
                <li><a href="{% url 'premier_league:stadium_list' %}">Stadiums</a></li>
                <li><a href="{% url 'premier_league:news_list' %}">News</a></li>
            </ul>
        </div>
        <div>
            {% if user.is_authenticated %}
                <p>Welcome, {{ user.username }}! <a href="{% url 'premier_league:logout' %}">Logout</a></p>
            {% else %}
                <p><a href="{% url 'premier_league:register' %}">Register</a> | <a
                        href="{% url 'premier_league:login' %}">Login</a></p>
            {% endif %}
        </div>
    </div>

   <div>
    <h2>Latest News</h2>
    <ul>
        {% for news in news_list %}
            <li>
                <h3>{{ news.shortname }}</h3>
                <p>{{ news.description }}</p>
                <p><a href="{% url 'premier_league:news_detail' news.pk %}">Read more</a></p>
                {% if user.is_authenticated %}
                    <p>
                        <a href="{% url 'premier_league:create_comment' news.pk %}">Comments</a>: {{ news.comments.count }}
                    </p>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

news_premier_league/premier_league/templates/premier_league/news_detail.html
{% extends 'base.html' %}
{% block title %}
    News
{% endblock %}
{% block body %}
    <h1>{{ news.shortname }}</h1>
    <p>Added: {{ news.created_at }}</p>
    <p>Description: {{ news.description }}</p>
    <p>Author: {{ news.author }}</p>
    <ul>
        <li>
            <a href="{% url 'premier_league:index' %}">Back to Home</a>
        </li>
    </ul>
{% endblock %}

news_premier_league/premier_league/templates/premier_league/news_list.html
{% extends 'base.html' %}
{% block title %}
    News
{% endblock %}
{% block body %}
    <h1>Latest News:</h1>
    <ul>
        {% for elem in news_list %}
            <li>
                <h3><a href="{% url 'premier_league:news_detail' elem.pk %}">{{ elem.shortname }}</a></h3>
                <p>Created at: {{ elem.created_at }}</p>
                <p>Comments: {{ elem.comments.count }}</p>
                {% if user.is_authenticated %}
                    <a href="{% url 'premier_league:news_detail' elem.pk %}">Read more</a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    <ul>
        <li>
            <a href="{% url 'premier_league:index' %}">Back to Home</a>
        </li>
    </ul>
{% endblock %}

news_premier_league/premier_league/templates/premier_league/stadium_detail.html
{% extends 'base.html' %}
{% block title %}
    Stadium Detail
{% endblock %}
{% block body %}
    <h1>{{ stadium.name }}</h1>
    <p>Location: {{ stadium.location }}</p>
    <p>Broke ground: {{ stadium.brokeground }}</p>
    <p>Capacity: {{ stadium.capacity }}</p>
    <p>Architect: {{ stadium.architect }}</p>
    <ul>
        <li>
            <a href="{% url 'premier_league:index' %}">Back to Home</a>
        </li>
    </ul>
{% endblock %}

news_premier_league/premier_league/templates/premier_league/stadium_list.html
{% extends 'base.html' %}
{% block title %}
    Stadiums
{% endblock %}
{% block body %}
    <h1>Stadium List</h1>
    <ul>
        {% for stadium in stadiums %}
            <li><a href="{% url 'premier_league:stadium_detail' stadium.pk %}">{{ stadium.name }}</a></li>
        {% endfor %}
    </ul>
    <ul>
        <li>
            <a href="{% url 'premier_league:index' %}">Back to Home</a>
        </li>
    </ul>
{% endblock %}

news_premier_league/premier_league/templates/premier_league/team_detail.html
{% extends 'base.html' %}
{% block title %}
    Club info
{% endblock %}
{% block body %}
    <h1>{{ team.name }}</h1>
    <p>Founded: {{ team.founded }}</p>
    <p>Shortname ground: {{ team.shortname }}</p>
    <p>Official Website: {{ team.website }}</p>
    <p>League: {{ team.league }}</p>
    <ul>
        <li>
            <a href="{% url 'premier_league:index' %}">Back to Home</a>
        </li>
    </ul>
{% endblock %}

news_premier_league/premier_league/templates/premier_league/team_list.html
{% extends 'base.html' %}
{% block title %}
    Clubs
{% endblock %}
{% block body %}
    <h1>Clubs List</h1>
    <ul>
        {% for team in teams %}
            <li><a href="{% url 'premier_league:team_detail' team.pk %}">{{ team.shortname }}</a></li>
        {% endfor %}
    </ul>
    <ul>
        <li>
            <a href="{% url 'premier_league:index' %}">Back to Home</a>
        </li>
    </ul>
{% endblock %}

news_premier_league/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>{% block title %}
        Base
    {% endblock %}</title>
</head>
<body>

{% block body %}

{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

news_premier_league/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Premier League Home
{% endblock %}

{% block body %}
    <div style="display: flex; justify-content: space-between;">
        <div>
            <h1>Welcome to the Premier League</h1>
            <ul>
                <li><a href="{% url 'premier_league:team_list' %}">Clubs</a></li>
                <li><a href="{% url 'premier_league:stadium_list' %}">Stadiums</a></li>
                <li><a href="{% url 'premier_league:news_list' %}">News</a></li>
            </ul>
        </div>
        <div>
            {% if user.is_authenticated %}
                <p>Welcome, {{ user.username }}! <a href="{% url 'premier_league:logout' %}">Logout</a></p>
            {% else %}
                <p><a href="{% url 'premier_league:register' %}">Register</a> | <a href="{% url 'premier_league:login' %}">Login</a></p>
            {% endif %}
        </div>
    </div>
{% endblock %}